apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- name: arocontainerregistry.azurecr.io/spring-petclinic
  newName: arocontainerregistry.azurecr.io/spring-petclinic
  newTag: "117"
